In [140]:
import matplotlib.pyplot as plt
import os
import gc
import cv2
import tifffile
import numpy as np
import pandas as pd
from skimage.feature import hog
from skimage import exposure
import cv2
%matplotlib inline

In [141]:
def resize_image(img):
    img = cv2.resize(img, (1024, 512))
    gc.collect()
    return img
def load_image(img_path):
    img = tifffile.imread(img_path)
    img = resize_image(img)
    gc.collect()
    return img

In [142]:
def load_dataset(df_path, folder_path):
    train_df = pd.read_csv(df_path, usecols = ['image_id', 'label'])
    images, image_labels = [], []
    
    for index in range(len(train_df)):
        img_id, label = train_df.image_id[index], train_df.label[index] 
        img_path = os.path.join(folder_path, img_id + '.tif')
        img = load_image(img_path)
        images.append(img)
        image_labels.append(label)
        print(f"Image {index + 1}/{754} loaded")
        del img, label
        gc.collect()
    return images, image_labels

In [143]:
dataset_path = r"E:\compressed_train"
train_df_path = r"E:\train.csv"

In [144]:
images, image_labels = load_dataset(train_df_path, dataset_path)

Image 1/754 loaded
Image 2/754 loaded
Image 3/754 loaded
Image 4/754 loaded
Image 5/754 loaded
Image 6/754 loaded
Image 7/754 loaded
Image 8/754 loaded
Image 9/754 loaded
Image 10/754 loaded
Image 11/754 loaded
Image 12/754 loaded
Image 13/754 loaded
Image 14/754 loaded
Image 15/754 loaded
Image 16/754 loaded
Image 17/754 loaded
Image 18/754 loaded
Image 19/754 loaded
Image 20/754 loaded
Image 21/754 loaded
Image 22/754 loaded
Image 23/754 loaded
Image 24/754 loaded
Image 25/754 loaded
Image 26/754 loaded
Image 27/754 loaded
Image 28/754 loaded
Image 29/754 loaded
Image 30/754 loaded
Image 31/754 loaded
Image 32/754 loaded
Image 33/754 loaded
Image 34/754 loaded
Image 35/754 loaded
Image 36/754 loaded
Image 37/754 loaded
Image 38/754 loaded
Image 39/754 loaded
Image 40/754 loaded
Image 41/754 loaded
Image 42/754 loaded
Image 43/754 loaded
Image 44/754 loaded
Image 45/754 loaded
Image 46/754 loaded
Image 47/754 loaded
Image 48/754 loaded
Image 49/754 loaded
Image 50/754 loaded
Image 51/

In [171]:
def apply_hog(resized_img):
    fd, hog_image = hog(resized_img, orientations=8, pixels_per_cell=(30, 30),cells_per_block=(2, 2), visualize=True, multichannel=True)
    del hog_image
    gc.collect()
    return fd

In [156]:
try:
    del stacked_img_features, stacked_labels
    gc.collect()
except:
    pass
stacked_im_features=np.empty((31680,))
stacked_labels=np.empty((1,))

In [178]:
s1=apply_hog(images[1])
print(s1)
result = s1.reshape([1, 16896 ])
print(result)

C:\Users\AILABSERVER\AppData\Local\Temp\ipykernel_11760\897579060.py:2: FutureWarning: `multichannel` is a deprecated argument name for `hog`. It will be removed in version 1.0. Please use `channel_axis` instead.
  fd, hog_image = hog(resized_img, orientations=8, pixels_per_cell=(30, 30),cells_per_block=(2, 2), visualize=True, multichannel=True)


[0. 0. 0. ... 0. 0. 0.]
[[0. 0. 0. ... 0. 0. 0.]]


In [159]:
for i in range(len(images)):
    stacked_im_features = np.vstack([stacked_im_features, apply_hog(images[i])])
    if image_labels[i]=='CE':
        stacked_labels = np.vstack([stacked_labels, 1])
    else:
        stacked_labels = np.vstack([stacked_labels, 0])
    print(f"Image {i+1} / 754 stacked")

C:\Users\AILABSERVER\AppData\Local\Temp\ipykernel_11760\2103692787.py:2: FutureWarning: `multichannel` is a deprecated argument name for `hog`. It will be removed in version 1.0. Please use `channel_axis` instead.
  fd, hog_image = hog(resized_img, orientations=8, pixels_per_cell=(30, 30),cells_per_block=(2, 2), visualize=True, multichannel=True)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 31680 and the array at index 1 has size 1

In [182]:
stacked=[]
l=[]

In [183]:
for i in range(len(images)):
    stacked.append(apply_hog(images[i]))
    if image_labels[i]=='CE':
        l.append(1)
    else:
        l.append(0)
    print(f"Image {i+1} / 754 stacked")

C:\Users\AILABSERVER\AppData\Local\Temp\ipykernel_11760\897579060.py:2: FutureWarning: `multichannel` is a deprecated argument name for `hog`. It will be removed in version 1.0. Please use `channel_axis` instead.
  fd, hog_image = hog(resized_img, orientations=8, pixels_per_cell=(30, 30),cells_per_block=(2, 2), visualize=True, multichannel=True)


Image 1 / 754 stacked
Image 2 / 754 stacked
Image 3 / 754 stacked
Image 4 / 754 stacked
Image 5 / 754 stacked
Image 6 / 754 stacked
Image 7 / 754 stacked
Image 8 / 754 stacked
Image 9 / 754 stacked
Image 10 / 754 stacked
Image 11 / 754 stacked
Image 12 / 754 stacked
Image 13 / 754 stacked
Image 14 / 754 stacked
Image 15 / 754 stacked
Image 16 / 754 stacked
Image 17 / 754 stacked
Image 18 / 754 stacked
Image 19 / 754 stacked
Image 20 / 754 stacked
Image 21 / 754 stacked
Image 22 / 754 stacked
Image 23 / 754 stacked
Image 24 / 754 stacked
Image 25 / 754 stacked
Image 26 / 754 stacked
Image 27 / 754 stacked
Image 28 / 754 stacked
Image 29 / 754 stacked
Image 30 / 754 stacked
Image 31 / 754 stacked
Image 32 / 754 stacked
Image 33 / 754 stacked
Image 34 / 754 stacked
Image 35 / 754 stacked
Image 36 / 754 stacked
Image 37 / 754 stacked
Image 38 / 754 stacked
Image 39 / 754 stacked
Image 40 / 754 stacked
Image 41 / 754 stacked
Image 42 / 754 stacked
Image 43 / 754 stacked
Image 44 / 754 stack

In [190]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
std_train=StandardScaler().fit_transform(stacked)
print(std_train)
X_train,X_test,Y_train,Y_test=train_test_split(std_train,l,test_size=0.33,random_state=1)

[[ 1.71300253  0.2151049   0.44880226 ... -0.26486163 -0.27679124
  -0.2727251 ]
 [-0.44351274 -0.27042362 -0.28388031 ... -0.26486163 -0.27679124
  -0.2727251 ]
 [ 0.79327023  3.13001557  2.72359427 ... -0.26486163 -0.27679124
  -0.2727251 ]
 ...
 [-0.44351274 -0.27042362 -0.28388031 ... -0.26486163 -0.27679124
  -0.2727251 ]
 [-0.44351274 -0.27042362 -0.28388031 ... -0.26486163 -0.27679124
  -0.2727251 ]
 [-0.44351274 -0.27042362 -0.28388031 ... -0.26486163 -0.27679124
  -0.2727251 ]]


In [191]:
from sklearn import tree
from sklearn.metrics import accuracy_score, confusion_matrix

In [192]:
dcc=tree.DecisionTreeClassifier().fit(X_train,Y_train)

In [193]:
dcc_predict=dcc.predict(X_test)

In [194]:
dcc_predict

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0])

In [195]:
print("confusion matrix of DecisionTreeClassifier : " + str(confusion_matrix(Y_test,dcc_predict)))

confusion matrix of DecisionTreeClassifier : [[ 18  59]
 [ 40 132]]


In [196]:
print("Accuracy for DecisionTreeClassifier : " + str(accuracy_score(Y_test, dcc_predict)*100)+"%")

Accuracy for DecisionTreeClassifier : 60.24096385542169%


In [197]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import ensemble
from sklearn import tree
from sklearn.metrics import accuracy_score, confusion_matrix
rf=ensemble.RandomForestClassifier(n_estimators=100).fit(X_train,Y_train)
rf_predict=rf.predict(X_test)
knc=KNeighborsClassifier().fit(X_train,Y_train)
knc_predict=knc.predict(X_test)
dcc=tree.DecisionTreeClassifier().fit(X_train,Y_train)
dcc_predict=dcc.predict(X_test)
#print(accuracy_score(Y_test,predict))
print("confusion matrix of RandomForest Classifier: " + str(confusion_matrix(Y_test,rf_predict)))
print("confusion matrix of KNeighbors Classifier: " + str(confusion_matrix(Y_test,knc_predict)))
print("confusion matrix of DecisionTreeClassifier : " + str(confusion_matrix(Y_test,dcc_predict)))
print("Accuracy for RandomForest Classifier: " + str(accuracy_score(Y_test, rf_predict)*100)+"%")
print("Accuracy for KNeighbors Classifier: " + str(accuracy_score(Y_test, knc_predict)*100)+"%")
print("Accuracy for DecisionTreeClassifier : " + str(accuracy_score(Y_test, dcc_predict)*100)+"%")

confusion matrix of RandomForest Classifier: [[  0  77]
 [  2 170]]
confusion matrix of KNeighbors Classifier: [[  7  70]
 [ 15 157]]
confusion matrix of DecisionTreeClassifier : [[ 15  62]
 [ 39 133]]
Accuracy for RandomForest Classifier: 68.27309236947792%
Accuracy for KNeighbors Classifier: 65.86345381526104%
Accuracy for DecisionTreeClassifier : 59.43775100401606%


In [198]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='poly', degree=8)  
svclassifier.fit(X_train, Y_train)

SVC(degree=8, kernel='poly')

In [199]:
svm_pred = svclassifier.predict(X_test) 

In [200]:
from sklearn.metrics import classification_report, confusion_matrix  
print("confusion matrix of svclassifier : " + str(confusion_matrix(Y_test, svm_pred)))
print("Accuracy for SVM Classifier: " + str(accuracy_score(Y_test, svm_pred)*100)+"%")
print(classification_report(Y_test, svm_pred))

confusion matrix of svclassifier : [[  0  77]
 [  0 172]]
Accuracy for SVM Classifier: 69.07630522088354%
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        77
           1       0.69      1.00      0.82       172

    accuracy                           0.69       249
   macro avg       0.35      0.50      0.41       249
weighted avg       0.48      0.69      0.56       249



C:\Users\AILABSERVER\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\AILABSERVER\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\AILABSERVER\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [201]:
from sklearn.metrics import roc_auc_score

In [202]:
print("Accuracy for RandomForest Classifier: " + str(roc_auc_score(Y_test, rf_predict)*100)+"%")
print("Accuracy for KNeighbors Classifier: " + str(roc_auc_score(Y_test, knc_predict)*100)+"%")
print("Accuracy for DecisionTreeClassifier : " + str(roc_auc_score(Y_test, dcc_predict)*100)+"%")
print("Accuracy for SVM Classifier: " + str(roc_auc_score(Y_test, svm_pred)*100)+"%")

Accuracy for RandomForest Classifier: 49.41860465116279%
Accuracy for KNeighbors Classifier: 50.184989429175474%
Accuracy for DecisionTreeClassifier : 48.403050437934155%
Accuracy for SVM Classifier: 50.0%


In [124]:
pip install xgboost

     -------------------------------------- 125.4/125.4 MB 7.0 MB/s eta 0:00:00



In [203]:
from xgboost import XGBClassifier, XGBRFClassifier

In [204]:
xgb_classifier = XGBClassifier().fit(X_train, Y_train)
xgbrf_classifier = XGBRFClassifier().fit(X_train, Y_train)

In [205]:
xgb_pred = xgb_classifier.predict(X_test)
xgbrf_pred = xgbrf_classifier.predict(X_test)

In [206]:
print("Accuracy for XGBClassifier : " + str(roc_auc_score(Y_test, xgb_pred)*100)+"%")
print("Accuracy for XGBRFClassifier: " + str(roc_auc_score(Y_test, xgbrf_pred)*100)+"%")

Accuracy for XGBClassifier : 50.85321655089098%
Accuracy for XGBRFClassifier: 51.725309574146785%
